version: "3"
services:

    database:
        image: postgres:10.4
        ports:
            - "5432:5432"
        env_file:
          - .env
        volumes:
            - ./postgres_data

    server_mes:
        build: .
        ports:
            - "8000:5000"
        depends_on:
            -   database
        env_file:
            -   .env